### PR TITLE
Add bounding box + tests + wiki

### PR DESCRIPTION
**Pull request by lispandfound**
This implements the request of @claudio525 in https://github.com/ucgmsim/Pre-processing/pull/230 to make `bounding_box` a qcore module, provide tests and a background wiki explanation. It also adds the github action from https://github.com/ucgmsim/github-wiki-test/pull/1 to qcore in the process of adding the wiki pages.

### CODE REVIEW

**Comment by lispandfound** [comment]
This PR should work but the qcore tests and Jenkins server are being weird and flaky. This can be a draft, I will make a new PR for qcore to migrate to GitHub actions and then we can merge this.

**Comment by lispandfound** [comment]
I've fixed the tests in the xyts module. Had no idea how flaky they are! we should really make them work better so I don't need to waste an hour fixing them.

**Comment by lispandfound** [comment]
@sungeunbae I have added a wiki description of alphashapes and why they are unsuitable for the task of minimum area bounding boxes.

**Review by claudio525 — APPROVED** [review]

**Review by sungeunbae — APPROVED** [review]

**Review by AndrewRidden-Harper — APPROVED** [review]
Fantastic documentation and figures! It was a pleasure to read :)

**Comment by sungeunbae** [comment]
> @sungeunbae I have added a wiki description of alphashapes and why they are unsuitable for the task of minimum area bounding boxes.

Yes, I noticed that - excellent work!

**Review by joelridden — APPROVED** [review]

**Pull request merged**
