### PR TITLE
Add static method to generate IM object from str

### PR DESCRIPTION
**Pull request by jasonmotha**
Add static method that can generate an IM object from the output of the get_im_name function, as found in IM_calc csv headers

### CODE REVIEW

**Comment by jasonmotha** [comment]
This doesn't look unuseful?

**Comment by jpa198** [comment]
This looks good, and should make it easier to grab the IM dataclass value, I need to use it more...
I haven't had much of a look at this before, but does the post_init component line work? It looks like it tries to call from_str on what ever is in the variable name, instead of the Components enum

**Comment by jpa198** [comment]
As an aside, should the ProcessType enum in constants get changed to mostly a dataclass? It feels too bloated to be an enum anymore. Not that it will change that much.

**Review by jpa198 — APPROVED** [review]

**Comment by jasonmotha** [comment]
Yeah. That whole bit of the submission workflow needs a refactor. I think changing it to a dataclass puts a bandaid over the wreck.

**Review by jpa198 — APPROVED** [review]

**Review by shot0829 — APPROVED** [review]

**Pull request merged**
