### PR TITLE
Support for Mahuika Milan nodes 

### PR DESCRIPTION
**Pull request by sungeunbae**
Mahuika Milan nodes' hostname is something like "wmc005".
When an environment is activated, it will check the hostname via platform.node() call to determine if this is Maui or Mahuika (or Nurion) then loads the correct config file (eg. machine_mahuika.json vs machine_maui.json ) 

This fix ensures the correct config file is loaded for a milan node.

### CODE REVIEW

**Comment by sungeunbae** [comment]
Possibly other Mahuika partitions (eg. hugemem) may need a similar treatment.

**Comment by sungeunbae** [comment]
I guess other Mahuika partitions (eg. hugemem) may need a similar treatment.

**Review by claudio525 — APPROVED** [review]

**Review by joelridden — DISMISSED** [review]

**Review by lispandfound — APPROVED** [review]

**Review by lispandfound — CHANGES_REQUESTED** [review]
Could you add the hugemem node support now so we don't have to add it later, if it is just a simple regex change?

**Comment by sungeunbae** [comment]
> Could you add the hugemem node support now so we don't have to add it later, if it is just a simple regex change?

There are many such partitions: As the node name patterns are not published, I just collected from squeue output, which may not be complete.

image

```
(python3_mahuika) sjn87@mahuika01: /nesi/project/nesi00213/Environments/sarah2024/qcore/qcore$ squeue |grep milan
50100412      joinsu   landcare0 ppa00        128    500G milan   Sep 11 21:16     1:32:58 RUNNING  wml067              
50100591      xwan754  uoa03263  t1209_H2CC    64     32G milan   Sep 11 21:12    22:27:56 RUNNING  wmc027              
50100618      xwan754  uoa03263  t1209_H2CC    64     32G milan   Sep 11 21:15    22:30:19 RUNNING  wmc032              

```

**Review by joelridden — APPROVED** [review]

**Review by AndrewRidden-Harper — APPROVED** [review]

**Review by lispandfound — APPROVED** [review]
Great!

**Pull request merged**
